version: '3.7'

services:
  frontend:
    container_name: frontend-staging
    image: frontend-staging
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - '127.0.0.1:3000:80'