version: "3.4"

services:
  frontend:
    container_name: frontend-dev
    image: frontend-dev
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    volumes:
      - ./:/app/
    ports:
      - 127.0.0.1:3000:3000