version: '3.7'

services:
  frontend:
    container_name: frontend-dev
    image: frontend-dev
    volumes:
       - ./:/app
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    ports:
      - '127.0.0.1:3000:80'