version: "3.4"

services:
  frontend-dev:
    container_name: frontend-dev
    image: frontend-dev
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    ports:
      - 127.0.0.1:3000:3000