import {
  IManufacturer,
  IMaterial,
  IModel,
  IOrder,
  IProcess,
  IUser,
} from "../interface/Interface";

export const TestOrderList: IOrder[] = [
  {
    date: new Date(),
    orderState: 0,
    orderId: 0,
    bill: undefined,
    processList: [
      {
        model: {
          name: "test",
          certificate: ["certificate"],
          date: "01.01.2023",
          license: "licens",
          tags: ["tag1", "tag2"],
          URI: "url",
        },
        material: { name: "Material 1" },
        manufacturer: { name: "Hersteller 1" },
      },
      {
        model: {
          name: "test",
          certificate: ["certificate"],
          date: "01.01.2023",
          license: "licens",
          tags: ["tag1", "tag2"],
          URI: "url",
        },
        material: { name: "Material 1324" },
        manufacturer: { name: "Hersteller 41" },
      },
      {
        model: {
          name: "test",
          certificate: ["certificate"],
          date: "01.01.2023",
          license: "licens",
          tags: ["tag1", "tag2"],
          URI: "url",
        },
        material: { name: "Material 14" },
        manufacturer: { name: "Hersteller 123" },
      },
      {
        model: {
          name: "test",
          certificate: ["certificate"],
          date: "01.01.2023",
          license: "licens",
          tags: ["tag1", "tag2"],
          URI: "url",
        },
        material: { name: "Material 14" },
        manufacturer: { name: "Hersteller 123" },
      },
      {
        model: {
          name: "test",
          certificate: ["certificate"],
          date: "01.01.2023",
          license: "licens",
          tags: ["tag1", "tag2"],
          URI: "url",
        },
        material: { name: "Material 14" },
        manufacturer: { name: "Hersteller 123" },
      },
      {
        model: {
          name: "test",
          certificate: ["certificate"],
          date: "01.01.2023",
          license: "licens",
          tags: ["tag1", "tag2"],
          URI: "url",
        },
        material: { name: "Material 14" },
        manufacturer: { name: "Hersteller 123" },
      },
      {
        model: {
          name: "test",
          certificate: ["certificate"],
          date: "01.01.2023",
          license: "licens",
          tags: ["tag1", "tag2"],
          URI: "url",
        },
        material: { name: "Material 14" },
        manufacturer: { name: "Hersteller 123" },
      },
      {
        model: {
          name: "test",
          certificate: ["certificate"],
          date: "01.01.2023",
          license: "licens",
          tags: ["tag1", "tag2"],
          URI: "url",
        },
        material: { name: "Material 14" },
        manufacturer: { name: "Hersteller 123" },
      },
      {
        model: {
          name: "test",
          certificate: ["certificate"],
          date: "01.01.2023",
          license: "licens",
          tags: ["tag1", "tag2"],
          URI: "url",
        },
        material: { name: "Material 14" },
        manufacturer: { name: "Hersteller 123" },
      },
      {
        model: {
          name: "test",
          certificate: ["certificate"],
          date: "01.01.2023",
          license: "licens",
          tags: ["tag1", "tag2"],
          URI: "url",
        },
        material: { name: "Material 14" },
        manufacturer: { name: "Hersteller 123" },
      },
      {
        model: {
          name: "test",
          certificate: ["certificate"],
          date: "01.01.2023",
          license: "licens",
          tags: ["tag1", "tag2"],
          URI: "url",
        },
        material: { name: "Material 14" },
        manufacturer: { name: "Hersteller 123" },
      },
      {
        model: {
          name: "test",
          certificate: ["certificate"],
          date: "01.01.2023",
          license: "licens",
          tags: ["tag1", "tag2"],
          URI: "url",
        },
        material: { name: "Material 14" },
        manufacturer: { name: "Hersteller 123" },
      },
      {
        model: {
          name: "test",
          certificate: ["certificate"],
          date: "01.01.2023",
          license: "licens",
          tags: ["tag1", "tag2"],
          URI: "url",
        },
        material: { name: "Material 14" },
        manufacturer: { name: "Hersteller 123" },
      },
      {
        model: {
          name: "test",
          certificate: ["certificate"],
          date: "01.01.2023",
          license: "licens",
          tags: ["tag1", "tag2"],
          URI: "url",
        },
        material: { name: "Material 14" },
        manufacturer: { name: "Hersteller 123" },
      },
      {
        model: {
          name: "test",
          certificate: ["certificate"],
          date: "01.01.2023",
          license: "licens",
          tags: ["tag1", "tag2"],
          URI: "url",
        },
        material: { name: "Material 14" },
        manufacturer: { name: "Hersteller 123" },
      },
      {
        model: {
          name: "test",
          certificate: ["certificate"],
          date: "01.01.2023",
          license: "licens",
          tags: ["tag1", "tag2"],
          URI: "url",
        },
        material: { name: "Material 14" },
        manufacturer: { name: "Hersteller 123" },
      },
      {
        model: {
          name: "test",
          certificate: ["certificate"],
          date: "01.01.2023",
          license: "licens",
          tags: ["tag1", "tag2"],
          URI: "url",
        },
        material: { name: "Material 14" },
        manufacturer: { name: "Hersteller 123" },
      },
      {
        model: {
          name: "test",
          certificate: ["certificate"],
          date: "01.01.2023",
          license: "licens",
          tags: ["tag1", "tag2"],
          URI: "url",
        },
        material: { name: "Material 14" },
        manufacturer: { name: "Hersteller 123" },
      },
    ],
  },
  {
    date: new Date(),
    orderState: 1,
    orderId: 1,
    bill: undefined,
    processList: [
      {
        model: {
          name: "test",
          certificate: ["certificate"],
          date: "01.01.2023",
          license: "licens",
          tags: ["tag1", "tag2"],
          URI: "url",
        },
        material: { name: "Material 1" },
        manufacturer: { name: "Hersteller 1" },
      },
    ],
  },
  {
    date: new Date(),
    orderState: 2,
    orderId: 2,
    bill: new File([], "Rechnung.pdf"),
    processList: [
      {
        model: {
          name: "test",
          certificate: ["certificate"],
          date: "01.01.2023",
          license: "licens",
          tags: ["tag1", "tag2"],
          URI: "url",
        },
        material: { name: "Material 1" },
        manufacturer: { name: "Hersteller 1" },
      },
    ],
  },
  {
    date: new Date(),
    orderState: 3,
    orderId: 3,
    bill: new File([], "Rechnung.pdf"),
    processList: [
      {
        model: {
          name: "test",
          certificate: ["certificate"],
          date: "01.01.2023",
          license: "licens",
          tags: ["tag1", "tag2"],
          URI: "url",
        },
        material: { name: "Material 1" },
        manufacturer: { name: "Hersteller 1" },
      },
    ],
  },
  {
    date: new Date(),
    orderState: 4,
    orderId: 4,
    bill: new File([], "Rechnung.pdf"),
    processList: [
      {
        model: {
          name: "test",
          certificate: ["certificate"],
          date: "01.01.2023",
          license: "licens",
          tags: ["tag1", "tag2"],
          URI: "url",
        },
        material: { name: "Material 1" },
        manufacturer: { name: "Hersteller 1" },
      },
    ],
  },
  {
    date: new Date(),
    orderState: 5,
    orderId: 5,
    bill: new File([], "Rechnung.pdf"),
    processList: [
      {
        model: {
          name: "test",
          certificate: ["certificate"],
          date: "01.01.2023",
          license: "licens",
          tags: ["tag1", "tag2"],
          URI: "url",
        },
        material: { name: "Material 1" },
        manufacturer: { name: "Hersteller 1" },
      },
    ],
  },
];

export const TestModelList: IModel[] = [
  {
    name: "test",
    certificate: ["certificate"],
    date: "01.01.2023",
    license: "licens",
    tags: ["tag1", "tag2"],
    URI: "url",
  },
  {
    name: "test",
    certificate: ["certificate"],
    date: "01.01.2023",
    license: "licens",
    tags: ["tag1", "tag2"],
    URI: "url",
  },
  {
    name: "test",
    certificate: ["certificate"],
    date: "01.01.2023",
    license: "licens",
    tags: ["tag1", "tag2"],
    URI: "url",
  },
  {
    name: "test",
    certificate: ["certificate"],
    date: "01.01.2023",
    license: "licens",
    tags: ["tag1", "tag2"],
    URI: "url",
  },
];

export const TestMaterialList: IMaterial[] = [
  {
    materialId: 0,
    name: "Material 0",
    propList: ["Eigenschaft 1", "Eigenschaft 2"],
  },
  {
    materialId: 1,
    name: "Material 1",
    propList: ["Eigenschaft 1", "Eigenschaft 2"],
  },
  {
    materialId: 2,
    name: "Material 2",
    propList: ["Eigenschaft 1", "Eigenschaft 2"],
  },
  {
    materialId: 3,
    name: "Material 3",
    propList: ["Eigenschaft 1", "Eigenschaft 2"],
  },
  {
    materialId: 4,
    name: "Material 4",
    propList: ["Eigenschaft 1", "Eigenschaft 2"],
  },
  {
    materialId: 5,
    name: "Material 5",
    propList: ["Eigenschaft 1", "Eigenschaft 2"],
  },
  {
    materialId: 6,
    name: "Material 6",
    propList: ["Eigenschaft 1", "Eigenschaft 2"],
  },
  {
    materialId: 7,
    name: "Material 7",
    propList: ["Eigenschaft 1", "Eigenschaft 2"],
  },
  {
    materialId: 8,
    name: "Material 8",
    propList: ["Eigenschaft 1", "Eigenschaft 2"],
  },
  {
    materialId: 9,
    name: "Material 9",
    propList: ["Eigenschaft 1", "Eigenschaft 2"],
  },
];

export const TestManufacturerList: IManufacturer[] = [
  {
    manufacturerId: 0,
    name: "Hersteller 0",
    propList: ["Eigenschaft 1", "Eigenschaft 2"],
    certificateList: ["Zertifikat 1", "Zertifikat 2"],
    distance: 32,
    productionTime: 4,
    deliverTime: 7,
  },
  {
    manufacturerId: 1,
    name: "Hersteller 1",
    propList: ["Eigenschaft 1", "Eigenschaft 2"],
    certificateList: ["Zertifikat 1", "Zertifikat 2"],
    distance: 43,
    productionTime: 9,
    deliverTime: 5,
  },
  {
    manufacturerId: 2,
    name: "Hersteller 2",
    propList: ["Eigenschaft 1", "Eigenschaft 2"],
    certificateList: ["Zertifikat 1", "Zertifikat 2"],
    distance: 47,
    productionTime: 3,
    deliverTime: 6,
  },
  {
    manufacturerId: 3,
    name: "Hersteller 3",
    propList: ["Eigenschaft 1", "Eigenschaft 2"],
    certificateList: ["Zertifikat 1", "Zertifikat 2"],
    distance: 6,
    productionTime: 8,
    deliverTime: 5,
  },
  {
    manufacturerId: 4,
    name: "Hersteller 4",
    propList: ["Eigenschaft 1", "Eigenschaft 2"],
    certificateList: ["Zertifikat 1", "Zertifikat 2"],
    distance: 14,
    productionTime: 7,
    deliverTime: 5,
  },
  {
    manufacturerId: 5,
    name: "Hersteller 5",
    propList: ["Eigenschaft 1", "Eigenschaft 2"],
    certificateList: ["Zertifikat 1", "Zertifikat 2"],
    distance: 16,
    productionTime: 2,
    deliverTime: 6,
  },
  {
    manufacturerId: 6,
    name: "Hersteller 6",
    propList: ["Eigenschaft 1", "Eigenschaft 2"],
    certificateList: ["Zertifikat 1", "Zertifikat 2"],
    distance: 34,
    productionTime: 9,
    deliverTime: 6,
  },
  {
    manufacturerId: 7,
    name: "Hersteller 7",
    propList: ["Eigenschaft 1", "Eigenschaft 2"],
    certificateList: ["Zertifikat 1", "Zertifikat 2"],
    distance: 21,
    productionTime: 6,
    deliverTime: 2,
  },
  {
    manufacturerId: 8,
    name: "Hersteller 8",
    propList: ["Eigenschaft 1", "Eigenschaft 2"],
    certificateList: ["Zertifikat 1", "Zertifikat 2"],
    distance: 22,
    productionTime: 1,
    deliverTime: 4,
  },
  {
    manufacturerId: 9,
    name: "Hersteller 9",
    propList: ["Eigenschaft 1", "Eigenschaft 2"],
    certificateList: ["Zertifikat 1", "Zertifikat 2"],
    distance: 12,
    productionTime: 4,
    deliverTime: 1,
  },
];

export const TestProcessList: IProcess[] = [
  {
    model: {
      name: "test",
      certificate: ["certificate"],
      date: "01.01.2023",
      license: "licens",
      tags: ["tag1", "tag2"],
      URI: "url",
    },
    material: { name: "Material 0" },
    manufacturer: { name: "Hersteller 0" },
  },
  {
    model: {
      name: "test",
      certificate: ["certificate"],
      date: "01.01.2023",
      license: "licens",
      tags: ["tag1", "tag2"],
      URI: "url",
    },
    material: { name: "Material 1" },
    manufacturer: { name: "Hersteller 1" },
  },
  {
    model: {
      name: "test",
      certificate: ["certificate"],
      date: "01.01.2023",
      license: "licens",
      tags: ["tag1", "tag2"],
      URI: "url",
    },
    material: { name: "Material 2" },
    manufacturer: { name: "Hersteller 2" },
  },
];

export const TestUser: IUser[] = [
  {
    name: "test_indefinit",
    email: "test@test.test",
    type: 0,
    created: "01.01.2023",
    accessed: "02.01.2023",
    updated: "03.01.2023",
  },
  {
    name: "test_client",
    email: "test@test.test",
    type: 1,
    created: "01.01.2023",
    accessed: "02.01.2023",
    updated: "03.01.2023",
  },
  {
    name: "test_contractor",
    email: "test@test.test",
    type: 2,
    created: "01.01.2023",
    accessed: "02.01.2023",
    updated: "03.01.2023",
  },
  {
    name: "test_admin",
    email: "test@test.test",
    type: 3,
    created: "01.01.2023",
    accessed: "02.01.2023",
    updated: "03.01.2023",
  },
];
