export const URL_Impressum:string = "https://magazin.semper-ki.org/impressum/";
export const URL_Datenschutz:string = "https://magazin.semper-ki.org/datenschutzerklaerung/";
export const URL_Magazin:string = "https://magazin.semper-ki.org/";
export const URL_Contact:string = "https://magazin.semper-ki.org/kontakt/";
export const URL_AboutUs:string = "https://magazin.semper-ki.org/kiss/";
export const URL_Mastodon:string = "https://SemperKI@wisskomm.social/@SemperKI";
export const URL_Instagram:string = "https://www.instagram.com/";
export const URL_LinkedIn:string = "https://www.linkedin.com/company/semper-ki/";
export const URL_Cookies:string = "https://magazin.semper-ki.org/cookie-richtlinie-eu/";
export const StaleTime_Hour:number = 60*60; // 1 hour
export const StaleTime_Day:number = 60*60*24; // 1 day
export const StaleTime_Week:number = 60*60*24*7; // 1 week
export const StaleTime_Month:number = 60*60*24*30; // 1 month
export const StaleTime_STD:number = StaleTime_Hour; 