
export const Icon3DPrinter = require("../assets/images/icons/3DPrinter.svg").default;
export const IconArrowR = require("../assets/images/icons/Arrow_R.svg").default;
export const IconBeaker= require("../assets/images/icons/Beaker.svg").default;
export const IconBug= require("../assets/images/icons/Bug.svg").default;
export const IconCart = require("../assets/images/icons/Cart.svg").default;
export const IconCheck = require("../assets/images/icons/Check.svg").default;
export const IconChecklist = require("../assets/images/icons/Checklist.svg").default;
export const IconDashboard = require("../assets/images/icons/Dashboard.svg").default;
export const IconDate = require("../assets/images/icons/Date.svg").default;
export const IconDelete = require("../assets/images/icons/Delete.svg").default;
export const IconDocument = require("../assets/images/icons/Document.svg").default;
export const IconExpand = require("../assets/images/icons/Expand.svg").default;
export const IconFactory = require("../assets/images/icons/Factory.svg").default;
export const IconFast = require("../assets/images/icons/Fast.svg").default;
export const IconFlag = require("../assets/images/icons/Flag.svg").default;
export const IconFlower = require("../assets/images/icons/Flower.svg").default;
export const IconGlas = require("../assets/images/icons/Glas.svg").default;
export const IconHeart = require("../assets/images/icons/Heart.svg").default;
export const IconHeartStroke = require("../assets/images/icons/Heart_Stroke.svg").default;
export const IconHouse = require("../assets/images/icons/House.svg").default;
export const IconLeaf = require("../assets/images/icons/Leaf.svg").default;
export const IconLock = require("../assets/images/icons/Lock.svg").default;
export const IconLogo = require("../assets/images/icons/Logo.svg").default;
export const IconLogout = require("../assets/images/icons/Logout.svg").default;
export const IconMail = require("../assets/images/icons/Mail.svg").default;
export const IconMenu = require("../assets/images/icons/Menu.svg").default;
export const IconMetal = require("../assets/images/icons/Metal.svg").default;
export const IconMinus = require("../assets/images/icons/Minus.svg").default;
export const IconModel = require("../assets/images/icons/Model.svg").default;
export const IconNewDocument = require("../assets/images/icons/NewDocument.svg").default;
export const IconO = require("../assets/images/icons/O.svg").default;
export const IconPackage = require("../assets/images/icons/Package.svg").default;
export const IconPerson = require("../assets/images/icons/Person.svg").default;
export const IconPlastic = require("../assets/images/icons/Plastic.svg").default;
export const IconPlus = require("../assets/images/icons/Plus.svg").default;
export const IconQuestionMark = require("../assets/images/icons/QuestionMark.svg").default;
export const IconSearch = require("../assets/images/icons/Search.svg").default;
export const IconSearchModel = require("../assets/images/icons/SearchModel.svg").default;
export const IconSearchPerson = require("../assets/images/icons/SearchPerson.svg").default;
export const IconShare = require("../assets/images/icons/Share.svg").default;
export const IconSupplyChain = require("../assets/images/icons/SupplyChain.svg").default;
export const IconTable = require("../assets/images/icons/Table.svg").default;
export const IconUpload = require("../assets/images/icons/Upload.svg").default;
export const IconX = require("../assets/images/icons/X.svg").default;

  export const getIconByName = (name:string) =>{
    switch (name) {
      case "Icon3DPrinter": return Icon3DPrinter;
      case "IconArrowR": return IconArrowR;
      case "IconBeaker": return IconBeaker;
      case "IconBug": return IconBug;
      case "IconCart": return IconCart;
      case "IconCheck": return IconCheck;
      case "IconChecklist": return IconChecklist;
      case "IconDashboard": return IconDashboard;
      case "IconDate": return IconDate;
      case "IconDelete": return IconDelete;
      case "IconDocument": return IconDocument;
      case "IconExpand": return IconExpand;
      case "IconFactory": return IconFactory;
      case "IconFast": return IconFast;
      case "IconFlag": return IconFlag;
      case "IconFlower": return IconFlower;
      case "IconGlas": return IconGlas;
      case "IconHeart": return IconHeart;
      case "IconHeartStroke": return IconHeartStroke;
      case "IconHouse": return IconHouse;
      case "IconLeaf": return IconLeaf;
      case "IconLock": return IconLock;
      case "IconLogo": return IconLogo;
      case "IconLogout": return IconLogout;
      case "IconMail": return IconMail;
      case "IconMenu": return IconMenu;
      case "IconMetal": return IconMetal;
      case "IconMinus": return IconMinus;
      case "IconModel": return IconModel;
      case "IconNewDocument": return IconNewDocument;
      case "IconO": return IconO;
      case "IconPackage": return IconPackage;
      case "IconPerson": return IconPerson;
      case "IconPlastic": return IconPlastic;
      case "IconPlus": return IconPlus;
      case "IconQuestionMark": return IconQuestionMark;
      case "IconSearch": return IconSearch;
      case "IconSearchModel": return IconSearchModel;
      case "IconSearchPerson": return IconSearchPerson;
      case "IconShare": return IconShare;
      case "IconSupplyChain": return IconSupplyChain;
      case "IconTable": return IconTable;
      case "IconUpload": return IconUpload;
      case "IconX": return IconX;
      default: return IconX;
    }
  }

